---
NTupleDir: NTuples

JZ1:
	-	Directory: user.bewilson.tauclassifier.800036.Py8EG_A14N23LO_jetjet_JZ1WwithSW_v0_output.root
	- is_tau: False
	-	Files:
		-	user.bewilson.26443658._000002.output.root
		-	user.bewilson.26443658._000004.output.root
		-	user.bewilson.26443658._000005.output.root
		-	user.bewilson.26443658._000008.output.root
		-	user.bewilson.26443658._000006.output.root
		-	user.bewilson.26443658._000007.output.root
		-	user.bewilson.26443658._000001.output.root
		-	user.bewilson.26443658._000003.output.root

Gammatautau:
	-	Directory: user.bewilson.TauClassifierV3.425200.Pythia8EvtGen_A14NNPDF23LO_Gammatautau_MassWeight_v0_output.root
	- is_tau: True
	-	Files:
		-	user.bewilson.27141150._000001.output.root
		-	user.bewilson.27141150._000007.output.root
		-	user.bewilson.27141150._000005.output.root
		-	user.bewilson.27141150._000008.output.root
		-	user.bewilson.27141150._000002.output.root
		-	user.bewilson.27141150._000004.output.root
		-	user.bewilson.27141150._000003.output.root
		-	user.bewilson.27141150._000006.output.root


JZ2:
	-	Directory: user.bewilson.tauclassifier.364702.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ2WithSW_v0_output.root
	- is_tau: False
	-	Files:
		-	user.bewilson.26443660._000006.output.root
		-	user.bewilson.26443660._000004.output.root
		-	user.bewilson.26443660._000007.output.root
		-	user.bewilson.26443660._000003.output.root
		-	user.bewilson.26443660._000002.output.root
		-	user.bewilson.26443660._000001.output.root
		-	user.bewilson.26443660._000005.output.root


JZ3:
	-	Directory: user.bewilson.tauclassifier.364703.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ3WithSW_v0_output.root
	- is_tau: False
	-	Files:
		-	user.bewilson.26443661._000009.output.root
		-	user.bewilson.26443661._000004.output.root
		-	user.bewilson.26443661._000010.output.root
		-	user.bewilson.26443661._000002.output.root
		-	user.bewilson.26443661._000005.output.root
		-	user.bewilson.26443661._000006.output.root
		-	user.bewilson.26443661._000003.output.root
		-	user.bewilson.26443661._000011.output.root
		-	user.bewilson.26443661._000008.output.root
		-	user.bewilson.26443661._000007.output.root
		-	user.bewilson.26443661._000001.output.root


JZ4:
	-	Directory: user.bewilson.tauclassifier.364704.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ4WithSW_v0_output.root
	- is_tau: False
	-	Files:
		-	user.bewilson.26443662._000001.output.root
		-	user.bewilson.26443662._000004.output.root
		-	user.bewilson.26443662._000003.output.root
		-	user.bewilson.26443662._000002.output.root


JZ5:
	-	Directory: user.bewilson.tauclassifier.364705.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ5WithSW_v0_output.root
	- is_tau: False
	-	Files:
		-	user.bewilson.26443663._000006.output.root
		-	user.bewilson.26443663._000003.output.root
		-	user.bewilson.26443663._000005.output.root
		-	user.bewilson.26443663._000008.output.root
		-	user.bewilson.26443663._000007.output.root
		-	user.bewilson.26443663._000004.output.root
		-	user.bewilson.26443663._000001.output.root
		-	user.bewilson.26443663._000002.output.root


JZ6:
	-	Directory: user.bewilson.tauclassifier.364706.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ6WithSW_v0_output.root
	- is_tau: False
	-	Files:
		-	user.bewilson.26443664._000004.output.root
		-	user.bewilson.26443664._000001.output.root
		-	user.bewilson.26443664._000002.output.root
		-	user.bewilson.26443664._000003.output.root
		-	user.bewilson.26443664._000006.output.root
		-	user.bewilson.26443664._000005.output.root


JZ7:
	-	Directory: user.bewilson.tauclassifier.364707.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ7WithSW_v0_output.root
	- is_tau: False
	-	Files:
		-	user.bewilson.26443665._000007.output.root
		-	user.bewilson.26443665._000017.output.root
		-	user.bewilson.26443665._000010.output.root
		-	user.bewilson.26443665._000013.output.root
		-	user.bewilson.26443665._000006.output.root
		-	user.bewilson.26443665._000004.output.root
		-	user.bewilson.26443665._000001.output.root
		-	user.bewilson.26443665._000008.output.root
		-	user.bewilson.26443665._000015.output.root
		-	user.bewilson.26443665._000009.output.root
		-	user.bewilson.26443665._000014.output.root
		-	user.bewilson.26443665._000011.output.root
		-	user.bewilson.26443665._000005.output.root
		-	user.bewilson.26443665._000012.output.root
		-	user.bewilson.26443665._000003.output.root
		-	user.bewilson.26443665._000002.output.root
		-	user.bewilson.26443665._000016.output.root


JZ8:
	-	Directory: user.bewilson.tauclassifier.364708.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ8WithSW_v0_output.root
	- is_tau: False
	-	Files:
		-	user.bewilson.26443666._000004.output.root
		-	user.bewilson.26443666._000001.output.root
		-	user.bewilson.26443666._000002.output.root
		-	user.bewilson.26443666._000003.output.root


